local data = require("scripts.data.game_data")
local config = require("scripts.config.game_config")

local function animate_button(node)
    gui.play_flipbook(node, "press_anim")
end

local function update_score_value(node)
    gui.set_text(node, tostring(data.get_score()))
end

local function update_balls_value(node)
    gui.set_text(node, tostring(data.get_balls_count()))
end

local function update_playing_balls_value(node)
    gui.set_text(node, tostring(data.get_playable_balls_count()))
end

local function update_recovery_time(node)
    local time_left = data.get_recovery_time_left()
    
    local minutes = math.floor(time_left / 60)
    local seconds = time_left % 60
    
    gui.set_text(node, string.format("+%d balls in %02d:%02d", config.regeneration.balls_count, minutes, seconds))
end

function init(self)
    self.run_button = gui.get_node("run_button")
    self.add_playing_ball_button = gui.get_node("add_playing_ball_button")
    self.remove_playing_ball_button = gui.get_node("remove_playing_ball_button")
    self.add_ball_button = gui.get_node("add_ball_button")
    self.add_balls_10_button = gui.get_node("add_balls_10_button")
    
    self.score_value_text = gui.get_node("score_value_text")
    self.current_balls_text = gui.get_node("current_balls_text")
    self.current_playing_balls_text = gui.get_node("current_playing_balls_text")
    self.recovery_timer_text = gui.get_node("recovery_timer_text")
    
    update_score_value(self.score_value_text)
    update_balls_value(self.current_balls_text)
    update_playing_balls_value(self.current_playing_balls_text)
    update_recovery_time(self.recovery_timer_text)
    
    msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
    if action_id == hash("click") and action.pressed then
        if self.run_button ~= nil and gui.pick_node(self.run_button, action.x, action.y) then
            animate_button(self.run_button)
            msg.post("game:/game_root", "spawn_ball")
        elseif self.add_playing_ball_button ~= nil and gui.pick_node(self.add_playing_ball_button, action.x, action.y) then
            msg.post("game:/game_root", "add_playing_ball", {amount = 1})
        elseif self.remove_playing_ball_button ~= nil and gui.pick_node(self.remove_playing_ball_button, action.x, action.y) then
            msg.post("game:/game_root", "add_playing_ball", {amount = -1})
        elseif self.add_ball_button ~= nil and gui.pick_node(self.add_ball_button, action.x, action.y) then
            animate_button(self.add_ball_button)
            msg.post("game:/game_root", "add_ball", {amount = 1})
        elseif self.add_balls_10_button ~= nil and gui.pick_node(self.add_balls_10_button, action.x, action.y) then
            animate_button(self.add_balls_10_button)
            msg.post("game:/game_root", "add_ball", {amount = 10})
        end
    end
end

function update(self, dt)
    update_recovery_time(self.recovery_timer_text)
end

function on_message(self, message_id, message, sender)
    if message_id == hash("ball_recovered") then
        update_balls_value(self.current_balls_text)
        update_recovery_time(self.recovery_timer_text)
    elseif message_id == hash("update_current_balls_text") then
        update_balls_value(self.current_balls_text)
    elseif message_id == hash("update_playing_balls_text") then
        update_playing_balls_value(self.current_playing_balls_text)
    elseif message_id == hash("update_score_text") then
        update_score_value(self.score_value_text)
    end
end

function final(self)
    msg.post(".", "release_input_focus")
end