function init(self)
    self.run_button = gui.get_node("run_button")
    msg.post(".", "acquire_input_focus")
end

local function animate_run_button(node)
    gui.play_flipbook(node, "press_anim")
end

function on_input(self, action_id, action)
    if action_id == hash("click") and action.pressed then
        if self.run_button ~= nil and gui.pick_node(self.run_button, action.x, action.y) then
            animate_run_button(self.run_button)
            msg.post("game:/game_root", "spawn_ball")
        end
    end
end

function final(self)
    msg.post(".", "release_input_focus")
end